import { performance } from 'node:perf_hooks'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { calculateStatementStats } from '../src/analysis/statementStats'
import { buildKeptExportRenderPlan } from '../src/export/keptExportLayout'
import { filterReviewEntries } from '../src/renderer/src/hooks/reviewFiltering'
import { filterInChunks } from '../src/renderer/src/hooks/useIncrementalReviewFilter'
import { runOcrOrchestration } from '../src/ocr/ocrOrchestrator'
import { extractDocumentTextLayer, projectParserEntries } from '../src/extraction'
import { ProjectStore } from '../src/main/projectStore'
import type { ProjectEntry, ProjectState, ReviewStatus } from '../src/shared/contracts'
import type { KeptExportTemplate, KeptExportSourceRow } from '../src/shared/keptExportTemplate'
import type { ParserExtractionResult } from '../src/extraction/types'

const PAGE_COUNT = 2_000
const ENTRY_COUNT = 2_000
const ITERATIONS = 5

interface Sample {
  label: string
  values: number[]
  unit: 'ms'
}

interface FixtureManifestEntry {
  id: string
  kind: string
  fixture: string
  purpose: string
}

const representativeFixtures: FixtureManifestEntry[] = [
  {
    id: 'digital-accounting',
    kind: 'digital',
    fixture: 'test-data/fixtures/digital-accounting-statement.json',
    purpose: 'born-digital accounting rows and totals'
  },
  {
    id: 'scanned-invoice',
    kind: 'scanned',
    fixture: 'test-data/fixtures/ocr-scanned-invoice.pdf',
    purpose: 'OCR-only input and cancellation/cleanup coverage'
  },
  {
    id: 'mixed-statement',
    kind: 'mixed',
    fixture: 'test-data/fixtures/ocr-mixed-statement.pdf',
    purpose: 'parser plus OCR merge coverage'
  },
  {
    id: 'multi-line-statement',
    kind: 'multi-line',
    fixture: 'test-data/fixtures/RichardPenderRevolut 2023 to 2026-part-1.pdf',
    purpose: 'continuation lines, payees, references, and reconciliation'
  },
  {
    id: 'duplicate-and-reference-review',
    kind: 'review',
    fixture: 'test-data/fixtures/2026-review.json',
    purpose: 'duplicate, reference, Keep/Maybe/Exclude, and review workflow data'
  },
  {
    id: 'large-project-profile',
    kind: 'large-project',
    fixture: 'generated by this benchmark: 2,000 pages and 2,000 entries',
    purpose: 'opening, filtering, navigation, and export performance'
  }
]

function now(): string {
  return new Date().toISOString()
}

function makeEntry(index: number, timestamp: string): ProjectEntry {
  const status: ReviewStatus = index % 11 === 0 ? 'maybe' : index % 17 === 0 ? 'exclude' : 'keep'
  const source = index % 5 === 0 ? 'ocr' : index % 7 === 0 ? 'merged' : 'parser'
  const amount = (index + 1).toFixed(2)
  return {
    id: `entry-${index + 1}`,
    rawText: `1 Mar 2026 Northwind Merchant ${index + 1} £${amount} £10,000.00`,
    normalizedText: `1 Mar 2026 Northwind Merchant ${index + 1} £${amount} £10,000.00`,
    payee: `Northwind Merchant ${index % 100}`,
    source,
    status,
    confidence: 0.55 + ((index * 17) % 45) / 100,
    regions: [
      {
        documentId: 'large-performance-document',
        pageNumber: (index % PAGE_COUNT) + 1,
        bbox: {
          x: 40,
          y: 80,
          width: 300,
          height: 14,
          coordinateSpace: 'pdf-points'
        }
      }
    ],
    category: index % 3 === 0 ? 'accounting-expense' : 'accounting-entry',
    tags: [
      'accounting',
      ...(index % 11 === 0 ? ['review:maybe'] : []),
      ...(index % 13 === 0 ? ['duplicate-candidate'] : [])
    ],
    createdAt: timestamp,
    updatedAt: timestamp
  }
}

function makeProject(): ProjectState {
  const timestamp = now()
  const store = new ProjectStore('sprint-0-benchmark-placeholder')
  const project = store.create('Sprint 0 large project', 'sprint-0-large-project')
  project.documents = [
    {
      id: 'large-performance-document',
      path: 'sprint-0-large-project.pdf',
      name: 'sprint-0-large-project.pdf',
      size: 1024 * 1024,
      pageCount: PAGE_COUNT,
      kind: 'tabular',
      importedAt: timestamp
    }
  ]
  project.pages = Array.from({ length: PAGE_COUNT }, (_, index) => ({
    documentId: 'large-performance-document',
    pageNumber: index + 1,
    width: 612,
    height: 792,
    rotation: 0 as const,
    kind: index % 5 === 0 ? ('mixed' as const) : ('text' as const),
    confidence: 0.9
  }))
  project.entries = Array.from({ length: ENTRY_COUNT }, (_, index) => makeEntry(index, timestamp))
  project.preflight = [
    {
      documentId: 'large-performance-document',
      kind: 'tabular',
      confidence: 0.9,
      completedAt: timestamp,
      pages: project.pages.map((page) => ({
        pageNumber: page.pageNumber,
        kind: page.kind,
        characterCount: 140,
        confidence: page.confidence ?? 0.9,
        ocrRecommended: page.kind !== 'text',
        rotation: page.rotation
      }))
    }
  ]
  return project
}

function makeReviewOptions(): Parameters<typeof filterReviewEntries>[1] {
  return {
    query: 'northwind',
    reviewStatus: 'all',
    reviewSource: 'all',
    reviewCategory: 'all',
    reviewIssueFilter: 'all',
    issuesByEntry: new Map()
  }
}

function makeExportTemplate(): KeptExportTemplate {
  const defaultTextStyle = {
    fontRef: { kind: 'standard-14' as const, family: 'Helvetica' },
    fontSize: 9,
    color: '#101010',
    fontWeight: 'normal' as const,
    fontStyle: 'normal' as const
  }
  const page = {
    pageSize: 'a4' as const,
    orientation: 'portrait' as const,
    layoutMode: 'table-row' as const,
    entriesPerPage: 40,
    defaultTextStyle,
    showReferenceUnderMainText: true,
    columns: [
      {
        id: 'payee',
        name: 'Payee',
        sourceField: 'payee' as const,
        x: 40,
        y: 60,
        width: 240,
        height: 14,
        spacing: 18,
        overflow: 'clip' as const
      },
      {
        id: 'date',
        name: 'Date',
        sourceField: 'date' as const,
        x: 290,
        y: 60,
        width: 90,
        height: 14,
        spacing: 18,
        overflow: 'clip' as const
      },
      {
        id: 'money-in',
        name: 'Money in',
        sourceField: 'money-in' as const,
        x: 390,
        y: 60,
        width: 90,
        height: 14,
        spacing: 18,
        overflow: 'clip' as const
      }
    ]
  }
  return { useSeparateLaterPages: false, pageOneTemplate: page, laterPagesTemplate: page }
}

function makeExportRows(entries: readonly ProjectEntry[]): KeptExportSourceRow[] {
  return entries.map((entry) => ({
    entryId: entry.id,
    values: {
      payee: entry.payee ?? entry.normalizedText,
      date: '1 Mar 2026',
      'money-in': '£10.00',
      reference: entry.id.endsWith('0') ? 'CARD-100' : ''
    }
  }))
}

function median(values: readonly number[]): number {
  const sorted = [...values].sort((left, right) => left - right)
  return sorted[Math.floor(sorted.length / 2)] ?? 0
}

function sample(label: string, operation: () => void): Sample {
  const values: number[] = []
  for (let iteration = 0; iteration < ITERATIONS; iteration += 1) {
    const start = performance.now()
    operation()
    values.push(performance.now() - start)
  }
  return { label, values, unit: 'ms' }
}

async function asyncSample(label: string, operation: () => Promise<void>): Promise<Sample> {
  const values: number[] = []
  for (let iteration = 0; iteration < ITERATIONS; iteration += 1) {
    const start = performance.now()
    await operation()
    values.push(performance.now() - start)
  }
  return { label, values, unit: 'ms' }
}

function formatSample(value: Sample): string {
  return `${median(value.values).toFixed(2)} ms median (${value.values
    .map((item) => item.toFixed(2))
    .join(', ')}; ${value.unit})`
}

function makeOcrParserResult(): ParserExtractionResult {
  const timestamp = now()
  const parserResult = extractDocumentTextLayer(
    'sprint-0-ocr-document',
    Array.from({ length: 4 }, (_, index) => ({
      documentId: 'sprint-0-ocr-document',
      pageNumber: index + 1,
      width: 612,
      height: 792,
      rotation: 0 as const,
      imageObjectCount: 1,
      items:
        index === 0
          ? [
              {
                str: 'Statement',
                transform: [1, 0, 0, 10, 40, 700] as const,
                width: 60,
                height: 10
              }
            ]
          : []
    })),
    timestamp
  )
  return parserResult
}

async function measureOcrCancellation(): Promise<void> {
  const parserResult = makeOcrParserResult()
  const controller = new AbortController()
  const canvas = { width: 600, height: 800, getContext: () => ({}) } as unknown as HTMLCanvasElement
  const start = performance.now()
  try {
    await runOcrOrchestration(
      {
        parserResult,
        parserEntries: projectParserEntries(parserResult, now()),
        pdf: { numPages: 4, getPage: async () => ({}) },
        settings: { mode: 'balanced', ocrLanguages: ['eng'] }
      },
      {
        signal: controller.signal,
        dependencies: {
          rasterize: async (documentId, _pdf, pages) => {
            controller.abort()
            return pages.map((pageNumber) => ({
              documentId,
              pageNumber,
              image: canvas,
              width: canvas.width,
              height: canvas.height
            }))
          },
          recognize: async () => []
        }
      }
    )
  } catch (error) {
    if (!(error instanceof DOMException) || error.name !== 'AbortError') throw error
  }
  if (canvas.width !== 0 || canvas.height !== 0)
    throw new Error('OCR canvas cleanup baseline failed.')
  ocrCancellationSamples.push(performance.now() - start)
}

const ocrCancellationSamples: number[] = []

async function main(): Promise<void> {
  const project = makeProject()
  const reviewOptions = makeReviewOptions()
  const samples: Sample[] = []
  const filterResult = filterReviewEntries(project.entries, reviewOptions)
  const financialStats = calculateStatementStats(
    project.entries,
    {
      amountColumns: ['money-out', 'money-in', 'balance'],
      dateSource: 'detected-date',
      descriptionSource: 'detected-description',
      referenceSource: 'entry-notes',
      categorySource: 'entry-category'
    },
    'all'
  )

  samples.push(
    sample('review filtering (2,000 entries)', () => {
      filterReviewEntries(project.entries, reviewOptions)
    })
  )
  samples.push(
    await asyncSample('incremental review filtering (2,000 entries)', async () => {
      await filterInChunks(project.entries, (entry) => entry.normalizedText.includes('northwind'))
    })
  )
  samples.push(
    sample('review navigation (2,000 entries)', () => {
      let checksum = 0
      for (let index = 0; index < filterResult.length; index += 1) {
        checksum += filterResult[index]?.id.length ?? 0
      }
      if (checksum === 0) throw new Error('Review navigation baseline produced no entries.')
    })
  )
  samples.push(
    sample('financial mapping and stats (2,000 entries)', () => {
      calculateStatementStats(
        project.entries,
        {
          amountColumns: ['money-out', 'money-in', 'balance'],
          dateSource: 'detected-date',
          descriptionSource: 'detected-description',
          referenceSource: 'entry-notes',
          categorySource: 'entry-category'
        },
        'all'
      )
    })
  )
  samples.push(
    sample('export preview render plan (2,000 entries)', () => {
      buildKeptExportRenderPlan(makeExportRows(project.entries), makeExportTemplate())
    })
  )

  const tempRoot = await mkdtemp(join(tmpdir(), 'exact-extract-sprint0-'))
  try {
    const store = new ProjectStore(tempRoot)
    await asyncSample('project save and reopen (2,000 pages / 2,000 entries)', async () => {
      await store.save(project)
      const loaded = await store.load(project.id)
      if (loaded.pages.length !== PAGE_COUNT || loaded.entries.length !== ENTRY_COUNT) {
        throw new Error('Project baseline reopened with incomplete data.')
      }
    }).then((result) => samples.push(result))
  } finally {
    await rm(tempRoot, { recursive: true, force: true })
  }

  for (let iteration = 0; iteration < ITERATIONS; iteration += 1) await measureOcrCancellation()
  samples.push({
    label: 'OCR cancellation and canvas cleanup',
    values: ocrCancellationSamples,
    unit: 'ms'
  })

  const report = [
    '# Sprint 0 performance baseline',
    '',
    `Generated: ${now()}`,
    `Node: ${process.version}`,
    `Fixture profile: ${PAGE_COUNT} pages / ${ENTRY_COUNT} entries`,
    `Iterations per measurement: ${ITERATIONS}`,
    '',
    '## Representative fixtures',
    '',
    '| ID | Kind | Fixture | Purpose |',
    '| --- | --- | --- | --- |',
    ...representativeFixtures.map(
      (fixture) => `| ${fixture.id} | ${fixture.kind} | ${fixture.fixture} | ${fixture.purpose} |`
    ),
    '',
    '## Measurements',
    '',
    '| Operation | Median | Target |',
    '| --- | ---: | ---: |',
    ...samples.map((value) => {
      const target = value.label.includes('project save')
        ? '< 1,000 ms'
        : value.label.includes('OCR')
          ? '< 100 ms'
          : value.label.includes('export')
            ? '< 500 ms'
            : '< 250 ms'
      return `| ${value.label} | ${formatSample(value)} | ${target} |`
    }),
    '',
    '## Interpretation',
    '',
    '- These are repeatable Node-side baselines, not claims about every installed machine.',
    '- OCR cancellation uses injected rasterization/recognition dependencies to measure orchestration cancellation and canvas cleanup without downloading or running a language model.',
    '- Future review, report, persistence, OCR, and export changes should rerun `npm run benchmark:sprint0` and compare medians against this profile.',
    '- The 2,000-page profile is intentionally generated so the benchmark does not depend on storing a huge binary fixture in the repository.'
  ].join('\n')

  process.stdout.write(`${report}\n`)

  // Keep the variable in the benchmark output path so the financial fixture is exercised too.
  if (financialStats.rows.length === 0)
    throw new Error('Financial fixture profile unexpectedly empty.')
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
